import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModalProvider } from "@/components/providers/ModalProvider";
const inter = Inter({ subsets: ["latin"] });
import { Nav } from "@/components/Nav";
import { NavLink } from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider/>

          <Nav>
        <NavLink href="/">Dashboard</NavLink>
        <NavLink href="/products">Books</NavLink>
        <NavLink href="/transaction">Transactions</NavLink>
        <NavLink href="/sales">Sales</NavLink>
      </Nav>
      <div className="container my-6">{children}</div>
            
         

        </ThemeProvider>
      </body>
    </html>
  );
}
